// <auto-generated />
using System;
using EduCoreSuite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduCoreSuite.Migrations
{
    [DbContext(typeof(ForgeDBContext))]
    [Migration("20250716100000_CreateCountySubCountyTables")]
    partial class CreateCountySubCountyTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Model definitions would be here, but we're only adding tables
            // so we don't need to define the entire model
#pragma warning restore 612, 618
        }
    }
}